apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecomm-ci-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abdessamadabidar/GitOps.git
    targetRevision: HEAD
    path: ecomm-ci-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
